# Generated by Django 5.1.4 on 2025-01-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='time_start',
        ),
    ]
