# Generated by Django 5.1.4 on 2025-01-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='questions',
            new_name='question',
        ),
    ]
